# Generated by Django 5.0 on 2023-12-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_consulta_nivel_riesgo_alter_consulta_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='nivel_riesgo',
            field=models.CharField(choices=[('Moderado', ' Moderado'), ('Intermedio', ' Intermedio'), ('Severo', 'Severo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10),
        ),
    ]
